<?php
require_once("database.php");

class m_phim extends database
{
    public function insert_phim($id, $name, $description, $thoi_luong, $rate, $avatar, $ngay_khoi_chieu, $trailer, $status)
    {
        $sql = "INSERT INTO phim VALUES (?,?,?,?,?,?,?,?,?)";
        $this->setQuery($sql);
        return $this->execute(array($id, $name, $description, $thoi_luong, $rate, $avatar, $ngay_khoi_chieu, $trailer, $status));
    }

    public function insert_the_loai_of_phim($id, $id_the_loai, $id_phim)
    {
        $sql = "INSERT INTO the_loai_of_phim values (?,?,?)";
        $this->setQuery($sql);
        return $this->execute(array($id, $id_the_loai, $id_phim));
    }

    public function read_phim()
    {
        $sql = "SELECT * from phim";
        $this->setQuery($sql);
        return $this->loadAllRows();
    }

    public function read_phim_by_id($id)
    {
        $sql = "SELECT * from phim where id = ?";
        $this->setQuery($sql);
        return $this->loadRow(array($id));
    }

    public function read_phim_by_name($name)
    {
        $sql = "SELECT * from phim where name=?";
        $this->setQuery($sql);
        return $this->loadRow(array($name));
    }

    public function edit_phim($name, $description, $thoi_luong, $rate, $avatar, $ngay_khoi_chieu, $trailer, $id)
    {
        $sql = "UPDATE phim set name = ?,description=?, thoi_luong=?,rate=?,avatar=?,ngay_khoi_chieu=?,trailer=? where id = ?";
        $this->setQuery($sql);
        return $this->execute(array($name, $description, $thoi_luong, $rate, $avatar, $ngay_khoi_chieu, $trailer, $id));
    }

    public function phim_delete($id)
    {
        $sql = "DELETE from phim where id=?";
        $this->setQuery($sql);
        return $this->execute(array($id));
    }

    public function active_phim($id)
    {
        $sql = "UPDATE phim set status=0 where id=?";
        $this->setQuery($sql);
        return $this->execute(array($id));
    }

    public function getLastId()
    {
        $sql="SELECT Max(id) as lastID FROM phim";
        $this->setQuery($sql);
        return $this->loadRow();
    }

//public function getLastId()
//{
//    return parent::getLastId(); // TODO: Change the autogenerated stub
//}

}
